/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/tto3pGfw6fd
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuItem } from "@/components/ui/dropdown-menu"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { Input } from "@/components/ui/input"
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Checkbox } from "@/components/ui/checkbox"

export function Retailer() {
  return (
    <div className="flex min-h-screen flex-col bg-background text-foreground">
      <header className="sticky top-0 z-40 border-b bg-background/80 backdrop-blur-sm">
        <div className="container flex h-16 items-center justify-between px-4 md:px-6">
          <Link href="#" className="flex items-center gap-2 font-bold" prefetch={false}>
            <LeafIcon className="h-6 w-6 text-primary" />
            FarmFresh
          </Link>
          <div className="flex items-center gap-4">
            <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <Button variant="ghost" className="flex items-center gap-2">
                  <MapPinIcon className="h-5 w-5" />
                  <span>San Francisco</span>
                  <ChevronDownIcon className="h-4 w-4" />
                </Button>
              </DropdownMenuTrigger>
              <DropdownMenuContent align="end" className="w-56">
                <DropdownMenuLabel>Select Location</DropdownMenuLabel>
                <DropdownMenuSeparator />
                <DropdownMenuItem>
                  <MapPinIcon className="mr-2 h-4 w-4" />
                  San Francisco
                </DropdownMenuItem>
                <DropdownMenuItem>
                  <MapPinIcon className="mr-2 h-4 w-4" />
                  Los Angeles
                </DropdownMenuItem>
                <DropdownMenuItem>
                  <MapPinIcon className="mr-2 h-4 w-4" />
                  New York
                </DropdownMenuItem>
                <DropdownMenuItem>
                  <MapPinIcon className="mr-2 h-4 w-4" />
                  Chicago
                </DropdownMenuItem>
              </DropdownMenuContent>
            </DropdownMenu>
            <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <Button variant="ghost" className="flex items-center gap-2">
                  <UserIcon className="h-5 w-5" />
                  <span>Account</span>
                  <ChevronDownIcon className="h-4 w-4" />
                </Button>
              </DropdownMenuTrigger>
              <DropdownMenuContent align="end" className="w-56">
                <DropdownMenuItem>
                  <UserIcon className="mr-2 h-4 w-4" />
                  Profile
                </DropdownMenuItem>
                <DropdownMenuItem>
                  <SettingsIcon className="mr-2 h-4 w-4" />
                  Settings
                </DropdownMenuItem>
                <DropdownMenuSeparator />
                <DropdownMenuItem>
                  <LogOutIcon className="mr-2 h-4 w-4" />
                  Logout
                </DropdownMenuItem>
              </DropdownMenuContent>
            </DropdownMenu>
            <Link href="#" className="relative" prefetch={false}>
              <ShoppingCartIcon className="h-6 w-6" />
              <Badge className="absolute -top-2 -right-2 rounded-full bg-primary px-2 py-1 text-xs text-primary-foreground">
                3
              </Badge>
            </Link>
          </div>
        </div>
      </header>
      <main className="flex-1">
        <section className="container py-8 px-4 md:px-6">
          <div className="grid gap-6 md:grid-cols-[1fr_300px]">
            <div>
              <h1 className="text-3xl font-bold">Discover Fresh Produce</h1>
              <p className="mt-2 text-muted-foreground">
                Browse our selection of locally-sourced farm lands and find the perfect produce for your needs.
              </p>
              <div className="mt-6 flex items-center gap-4">
                <Input type="search" placeholder="Search for produce..." className="flex-1" />
                <Button>Search</Button>
              </div>
            </div>
            <div className="grid gap-4">
              <Card>
                <CardHeader>
                  <CardTitle>Filter by Category</CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="grid gap-2">
                    <Label className="flex items-center gap-2">
                      <Checkbox />
                      Vegetables
                    </Label>
                    <Label className="flex items-center gap-2">
                      <Checkbox />
                      Fruits
                    </Label>
                    <Label className="flex items-center gap-2">
                      <Checkbox />
                      Grains
                    </Label>
                    <Label className="flex items-center gap-2">
                      <Checkbox />
                      Dairy
                    </Label>
                    <Label className="flex items-center gap-2">
                      <Checkbox />
                      Meat
                    </Label>
                  </div>
                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <CardTitle>Filter by Availability</CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="grid gap-2">
                    <Label className="flex items-center gap-2">
                      <Checkbox />
                      In Stock
                    </Label>
                    <Label className="flex items-center gap-2">
                      <Checkbox />
                      Out of Stock
                    </Label>
                  </div>
                </CardContent>
              </Card>
            </div>
          </div>
        </section>
        <section className="container py-8 px-4 md:px-6">
          <h2 className="text-2xl font-bold">Featured Farm Lands</h2>
          <div className="mt-6 grid gap-6 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
            <Card>
              <Link href="#" className="group relative block h-48 overflow-hidden rounded-lg" prefetch={false}>
                <img
                  src="/placeholder.svg"
                  alt="Farm Land"
                  width={400}
                  height={300}
                  className="h-full w-full object-cover transition-all duration-300 group-hover:scale-105"
                  style={{ aspectRatio: "400/300", objectFit: "cover" }}
                />
                <div className="absolute inset-0 bg-gradient-to-t from-black/80 to-transparent" />
                <div className="absolute bottom-0 left-0 right-0 px-4 py-3">
                  <h3 className="text-lg font-bold text-white">Sunny Acres Farm</h3>
                  <p className="mt-1 text-sm text-white/80">Organic Produce, Locally Grown</p>
                </div>
              </Link>
              <CardContent className="mt-4">
                <div className="flex items-center justify-between">
                  <div>
                    <h4 className="text-lg font-semibold">Potatoes</h4>
                    <p className="text-muted-foreground">In Stock</p>
                  </div>
                  <Button size="sm">Add to Cart</Button>
                </div>
              </CardContent>
            </Card>
            <Card>
              <Link href="#" className="group relative block h-48 overflow-hidden rounded-lg" prefetch={false}>
                <img
                  src="/placeholder.svg"
                  alt="Farm Land"
                  width={400}
                  height={300}
                  className="h-full w-full object-cover transition-all duration-300 group-hover:scale-105"
                  style={{ aspectRatio: "400/300", objectFit: "cover" }}
                />
                <div className="absolute inset-0 bg-gradient-to-t from-black/80 to-transparent" />
                <div className="absolute bottom-0 left-0 right-0 px-4 py-3">
                  <h3 className="text-lg font-bold text-white">Green Valley Farms</h3>
                  <p className="mt-1 text-sm text-white/80">Sustainable Farming Practices</p>
                </div>
              </Link>
              <CardContent className="mt-4">
                <div className="flex items-center justify-between">
                  <div>
                    <h4 className="text-lg font-semibold">Tomatoes</h4>
                    <p className="text-muted-foreground">In Stock</p>
                  </div>
                  <Button size="sm">Add to Cart</Button>
                </div>
              </CardContent>
            </Card>
            <Card>
              <Link href="#" className="group relative block h-48 overflow-hidden rounded-lg" prefetch={false}>
                <img
                  src="/placeholder.svg"
                  alt="Farm Land"
                  width={400}
                  height={300}
                  className="h-full w-full object-cover transition-all duration-300 group-hover:scale-105"
                  style={{ aspectRatio: "400/300", objectFit: "cover" }}
                />
                <div className="absolute inset-0 bg-gradient-to-t from-black/80 to-transparent" />
                <div className="absolute bottom-0 left-0 right-0 px-4 py-3">
                  <h3 className="text-lg font-bold text-white">Meadow View Farm</h3>
                  <p className="mt-1 text-sm text-white/80">Organic Fruits and Vegetables</p>
                </div>
              </Link>
              <CardContent className="mt-4">
                <div className="flex items-center justify-between">
                  <div>
                    <h4 className="text-lg font-semibold">Apples</h4>
                    <p className="text-muted-foreground">In Stock</p>
                  </div>
                  <Button size="sm">Add to Cart</Button>
                </div>
              </CardContent>
            </Card>
            <Card>
              <Link href="#" className="group relative block h-48 overflow-hidden rounded-lg" prefetch={false}>
                <img
                  src="/placeholder.svg"
                  alt="Farm Land"
                  width={400}
                  height={300}
                  className="h-full w-full object-cover transition-all duration-300 group-hover:scale-105"
                  style={{ aspectRatio: "400/300", objectFit: "cover" }}
                />
                <div className="absolute inset-0 bg-gradient-to-t from-black/80 to-transparent" />
                <div className="absolute bottom-0 left-0 right-0 px-4 py-3">
                  <h3 className="text-lg font-bold text-white">Hillside Orchard</h3>
                  <p className="mt-1 text-sm text-white/80">Fresh Fruits and Berries</p>
                </div>
              </Link>
              <CardContent className="mt-4">
                <div className="flex items-center justify-between">
                  <div>
                    <h4 className="text-lg font-semibold">Blueberries</h4>
                    <p className="text-muted-foreground">In Stock</p>
                  </div>
                  <Button size="sm">Add to Cart</Button>
                </div>
              </CardContent>
            </Card>
          </div>
        </section>
      </main>
      <footer className="border-t bg-background/80 py-6 backdrop-blur-sm">
        <div className="container flex items-center justify-between px-4 md:px-6">
          <div className="flex items-center gap-2">
            <LeafIcon className="h-6 w-6 text-primary" />
            <span className="text-sm text-muted-foreground">&copy; 2023 FarmFresh. All rights reserved.</span>
          </div>
          <div className="flex items-center gap-4">
            <Link href="#" className="text-sm text-muted-foreground hover:text-foreground" prefetch={false}>
              Privacy Policy
            </Link>
            <Link href="#" className="text-sm text-muted-foreground hover:text-foreground" prefetch={false}>
              Terms of Service
            </Link>
          </div>
        </div>
      </footer>
    </div>
  )
}

function ChevronDownIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m6 9 6 6 6-6" />
    </svg>
  )
}


function LeafIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M11 20A7 7 0 0 1 9.8 6.1C15.5 5 17 4.48 19 2c1 2 2 4.18 2 8 0 5.5-4.78 10-10 10Z" />
      <path d="M2 21c0-3 1.85-5.36 5.08-6C9.5 14.52 12 13 13 12" />
    </svg>
  )
}


function LogOutIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4" />
      <polyline points="16 17 21 12 16 7" />
      <line x1="21" x2="9" y1="12" y2="12" />
    </svg>
  )
}


function MapPinIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20 10c0 6-8 12-8 12s-8-6-8-12a8 8 0 0 1 16 0Z" />
      <circle cx="12" cy="10" r="3" />
    </svg>
  )
}


function SettingsIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12.22 2h-.44a2 2 0 0 0-2 2v.18a2 2 0 0 1-1 1.73l-.43.25a2 2 0 0 1-2 0l-.15-.08a2 2 0 0 0-2.73.73l-.22.38a2 2 0 0 0 .73 2.73l.15.1a2 2 0 0 1 1 1.72v.51a2 2 0 0 1-1 1.74l-.15.09a2 2 0 0 0-.73 2.73l.22.38a2 2 0 0 0 2.73.73l.15-.08a2 2 0 0 1 2 0l.43.25a2 2 0 0 1 1 1.73V20a2 2 0 0 0 2 2h.44a2 2 0 0 0 2-2v-.18a2 2 0 0 1 1-1.73l.43-.25a2 2 0 0 1 2 0l.15.08a2 2 0 0 0 2.73-.73l.22-.39a2 2 0 0 0-.73-2.73l-.15-.08a2 2 0 0 1-1-1.74v-.5a2 2 0 0 1 1-1.74l.15-.09a2 2 0 0 0 .73-2.73l-.22-.38a2 2 0 0 0-2.73-.73l-.15.08a2 2 0 0 1-2 0l-.43-.25a2 2 0 0 1-1-1.73V4a2 2 0 0 0-2-2z" />
      <circle cx="12" cy="12" r="3" />
    </svg>
  )
}


function ShoppingCartIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="8" cy="21" r="1" />
      <circle cx="19" cy="21" r="1" />
      <path d="M2.05 2.05h2l2.66 12.42a2 2 0 0 0 2 1.58h9.78a2 2 0 0 0 1.95-1.57l1.65-7.43H5.12" />
    </svg>
  )
}


function UserIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>
  )
}
